name: clean_architecture
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.1
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  cached_network_image: ^3.4.0
  geolocator: ^12.0.0
  lottie: ^2.7.0
  connectivity_plus: ^6.1.1
  google_maps_flutter: ^2.2.4
  cupertino_icons: ^1.0.8
  http: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/asgard_logo.png
    - assets/loading.json
    - assets/no_internet.json
    - assets/zero_products.json
    - assets/error.json

